package test

import (
	"context"
	"net/http"
	"testing"
	"time"

	"github.com/brokenbots/criteriadb/pkg/memory"
	pb "github.com/brokenbots/criteriadb/pkg/pb/criteriadb/v1"
)

func TestLiveOllamaEmbeddingEndpoint(t *testing.T) {
	// Check if local Ollama server is reachable
	client := &http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get("http://localhost:11434/api/tags")
	if err != nil || resp.StatusCode != http.StatusOK {
		t.Skip("Local Ollama endpoint http://localhost:11434 not reachable, skipping live Ollama test")
	}
	resp.Body.Close()

	ctx := context.Background()
	ollamaURL := "http://localhost:11434/v1/embeddings"
	modelName := "embeddinggemma:latest"

	t.Logf("Connecting to live local Ollama endpoint at %s using model %s...", ollamaURL, modelName)

	engine, err := memory.NewMemoryEngine(memory.Config{
		EmbeddingEndpoint: ollamaURL,
		EmbeddingModel:    modelName,
	})
	if err != nil {
		t.Fatalf("Failed to initialize engine: %v", err)
	}
	defer engine.Close()

	// 1. Remember node and let engine call live Ollama server to auto-embed
	node1 := &pb.MemoryNode{
		Id:      "live-ollama-node-1",
		Label:   "Golang Microservice Refactoring",
		Summary: "Optimized gRPC stream handlers and memory allocation in Go binary",
	}

	id, err := engine.Remember(ctx, node1, nil)
	if err != nil || id != "live-ollama-node-1" {
		t.Fatalf("Failed to remember node via live Ollama: %v", err)
	}

	if len(node1.GetPackedEmbedding()) == 0 {
		t.Fatalf("Expected packed_embedding to be generated by live Ollama, got 0 bytes")
	}

	unpackedVec := memory.UnpackFloats(node1.GetPackedEmbedding())
	t.Logf("Successfully generated live embedding vector with %d dimensions!", len(unpackedVec))

	// 2. Perform live vector recall by passing query text
	results, err := engine.Recall(ctx, &pb.QueryRequest{
		QueryText: "Go memory optimization and gRPC",
	})
	if err != nil || len(results) == 0 {
		t.Fatalf("Failed live Ollama vector recall: %v", err)
	}

	t.Logf("Live Vector Similarity Search Success! Top result ID: %s, Score: %.4f, VectorScore: %.4f",
		results[0].Node.GetId(), results[0].Score, results[0].VectorScore)

	if results[0].Node.GetId() != "live-ollama-node-1" {
		t.Errorf("Expected live-ollama-node-1, got %s", results[0].Node.GetId())
	}
}
