// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: criteriadb/v1/criteriadb.proto

package criteriadbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tense int32

const (
	Tense_TENSE_UNSPECIFIED Tense = 0
	Tense_TENSE_PAST        Tense = 1
	Tense_TENSE_PRESENT     Tense = 2
	Tense_TENSE_FUTURE      Tense = 3
	Tense_TENSE_PLANNED     Tense = 4
	Tense_TENSE_CONDITIONAL Tense = 5
)

// Enum value maps for Tense.
var (
	Tense_name = map[int32]string{
		0: "TENSE_UNSPECIFIED",
		1: "TENSE_PAST",
		2: "TENSE_PRESENT",
		3: "TENSE_FUTURE",
		4: "TENSE_PLANNED",
		5: "TENSE_CONDITIONAL",
	}
	Tense_value = map[string]int32{
		"TENSE_UNSPECIFIED": 0,
		"TENSE_PAST":        1,
		"TENSE_PRESENT":     2,
		"TENSE_FUTURE":      3,
		"TENSE_PLANNED":     4,
		"TENSE_CONDITIONAL": 5,
	}
)

func (x Tense) Enum() *Tense {
	p := new(Tense)
	*p = x
	return p
}

func (x Tense) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tense) Descriptor() protoreflect.EnumDescriptor {
	return file_criteriadb_v1_criteriadb_proto_enumTypes[0].Descriptor()
}

func (Tense) Type() protoreflect.EnumType {
	return &file_criteriadb_v1_criteriadb_proto_enumTypes[0]
}

func (x Tense) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tense.Descriptor instead.
func (Tense) EnumDescriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{0}
}

type VisibilityScope int32

const (
	VisibilityScope_VISIBILITY_PRIVATE  VisibilityScope = 0 // Visible only to creator adapter
	VisibilityScope_VISIBILITY_WORKFLOW VisibilityScope = 1 // Visible to all adapters within the same workflow run
	VisibilityScope_VISIBILITY_GLOBAL   VisibilityScope = 2 // Visible across all workflow runs & adapters
)

// Enum value maps for VisibilityScope.
var (
	VisibilityScope_name = map[int32]string{
		0: "VISIBILITY_PRIVATE",
		1: "VISIBILITY_WORKFLOW",
		2: "VISIBILITY_GLOBAL",
	}
	VisibilityScope_value = map[string]int32{
		"VISIBILITY_PRIVATE":  0,
		"VISIBILITY_WORKFLOW": 1,
		"VISIBILITY_GLOBAL":   2,
	}
)

func (x VisibilityScope) Enum() *VisibilityScope {
	p := new(VisibilityScope)
	*p = x
	return p
}

func (x VisibilityScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityScope) Descriptor() protoreflect.EnumDescriptor {
	return file_criteriadb_v1_criteriadb_proto_enumTypes[1].Descriptor()
}

func (VisibilityScope) Type() protoreflect.EnumType {
	return &file_criteriadb_v1_criteriadb_proto_enumTypes[1]
}

func (x VisibilityScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityScope.Descriptor instead.
func (VisibilityScope) EnumDescriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{1}
}

type TemporalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Tense         Tense                  `protobuf:"varint,5,opt,name=tense,proto3,enum=criteriadb.v1.Tense" json:"tense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalInfo) Reset() {
	*x = TemporalInfo{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalInfo) ProtoMessage() {}

func (x *TemporalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalInfo.ProtoReflect.Descriptor instead.
func (*TemporalInfo) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{0}
}

func (x *TemporalInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TemporalInfo) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *TemporalInfo) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *TemporalInfo) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *TemporalInfo) GetTense() Tense {
	if x != nil {
		return x.Tense
	}
	return Tense_TENSE_UNSPECIFIED
}

type DigitalLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Machine       string                 `protobuf:"bytes,1,opt,name=machine,proto3" json:"machine,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	Project       string                 `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	FolderPath    string                 `protobuf:"bytes,4,opt,name=folder_path,json=folderPath,proto3" json:"folder_path,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	ServiceUrl    string                 `protobuf:"bytes,6,opt,name=service_url,json=serviceUrl,proto3" json:"service_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalLocation) Reset() {
	*x = DigitalLocation{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalLocation) ProtoMessage() {}

func (x *DigitalLocation) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalLocation.ProtoReflect.Descriptor instead.
func (*DigitalLocation) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{1}
}

func (x *DigitalLocation) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *DigitalLocation) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *DigitalLocation) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DigitalLocation) GetFolderPath() string {
	if x != nil {
		return x.FolderPath
	}
	return ""
}

func (x *DigitalLocation) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *DigitalLocation) GetServiceUrl() string {
	if x != nil {
		return x.ServiceUrl
	}
	return ""
}

type PhysicalLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Venue         string                 `protobuf:"bytes,1,opt,name=venue,proto3" json:"venue,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhysicalLocation) Reset() {
	*x = PhysicalLocation{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhysicalLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhysicalLocation) ProtoMessage() {}

func (x *PhysicalLocation) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhysicalLocation.ProtoReflect.Descriptor instead.
func (*PhysicalLocation) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{2}
}

func (x *PhysicalLocation) GetVenue() string {
	if x != nil {
		return x.Venue
	}
	return ""
}

func (x *PhysicalLocation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PhysicalLocation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PhysicalLocation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type AgentScope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CreatorAdapterId   string                 `protobuf:"bytes,1,opt,name=creator_adapter_id,json=creatorAdapterId,proto3" json:"creator_adapter_id,omitempty"`       // e.g. "copilot-dev-1", "shell-runner"
	CreatorAdapterType string                 `protobuf:"bytes,2,opt,name=creator_adapter_type,json=creatorAdapterType,proto3" json:"creator_adapter_type,omitempty"` // e.g. "copilot", "shell", "claude", "mcp"
	CreatorAgentId     string                 `protobuf:"bytes,3,opt,name=creator_agent_id,json=creatorAgentId,proto3" json:"creator_agent_id,omitempty"`             // e.g. "agent-alpha"
	Visibility         VisibilityScope        `protobuf:"varint,4,opt,name=visibility,proto3,enum=criteriadb.v1.VisibilityScope" json:"visibility,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentScope) Reset() {
	*x = AgentScope{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentScope) ProtoMessage() {}

func (x *AgentScope) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentScope.ProtoReflect.Descriptor instead.
func (*AgentScope) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{3}
}

func (x *AgentScope) GetCreatorAdapterId() string {
	if x != nil {
		return x.CreatorAdapterId
	}
	return ""
}

func (x *AgentScope) GetCreatorAdapterType() string {
	if x != nil {
		return x.CreatorAdapterType
	}
	return ""
}

func (x *AgentScope) GetCreatorAgentId() string {
	if x != nil {
		return x.CreatorAgentId
	}
	return ""
}

func (x *AgentScope) GetVisibility() VisibilityScope {
	if x != nil {
		return x.Visibility
	}
	return VisibilityScope_VISIBILITY_PRIVATE
}

type MemoryNode struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label   string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Type    string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // e.g. "event", "fact", "person", "task", "artifact"
	Summary string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	// Optional: Packed float32 vector embedding bytes or empty for Zero-LLM mode
	PackedEmbedding  []byte            `protobuf:"bytes,5,opt,name=packed_embedding,json=packedEmbedding,proto3" json:"packed_embedding,omitempty"`
	VectorDimension  int32             `protobuf:"varint,6,opt,name=vector_dimension,json=vectorDimension,proto3" json:"vector_dimension,omitempty"`
	Temporal         *TemporalInfo     `protobuf:"bytes,7,opt,name=temporal,proto3" json:"temporal,omitempty"`
	DigitalLocation  *DigitalLocation  `protobuf:"bytes,8,opt,name=digital_location,json=digitalLocation,proto3" json:"digital_location,omitempty"`
	PhysicalLocation *PhysicalLocation `protobuf:"bytes,9,opt,name=physical_location,json=physicalLocation,proto3" json:"physical_location,omitempty"`
	AgentScope       *AgentScope       `protobuf:"bytes,10,opt,name=agent_scope,json=agentScope,proto3" json:"agent_scope,omitempty"`
	Properties       *structpb.Struct  `protobuf:"bytes,11,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemoryNode) Reset() {
	*x = MemoryNode{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryNode) ProtoMessage() {}

func (x *MemoryNode) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryNode.ProtoReflect.Descriptor instead.
func (*MemoryNode) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MemoryNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MemoryNode) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *MemoryNode) GetPackedEmbedding() []byte {
	if x != nil {
		return x.PackedEmbedding
	}
	return nil
}

func (x *MemoryNode) GetVectorDimension() int32 {
	if x != nil {
		return x.VectorDimension
	}
	return 0
}

func (x *MemoryNode) GetTemporal() *TemporalInfo {
	if x != nil {
		return x.Temporal
	}
	return nil
}

func (x *MemoryNode) GetDigitalLocation() *DigitalLocation {
	if x != nil {
		return x.DigitalLocation
	}
	return nil
}

func (x *MemoryNode) GetPhysicalLocation() *PhysicalLocation {
	if x != nil {
		return x.PhysicalLocation
	}
	return nil
}

func (x *MemoryNode) GetAgentScope() *AgentScope {
	if x != nil {
		return x.AgentScope
	}
	return nil
}

func (x *MemoryNode) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

type MemoryEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Relation      string                 `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"` // e.g. "INVOLVES", "DEPENDS_ON", "LOCATED_AT"
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Temporal      *TemporalInfo          `protobuf:"bytes,6,opt,name=temporal,proto3" json:"temporal,omitempty"`
	AgentScope    *AgentScope            `protobuf:"bytes,7,opt,name=agent_scope,json=agentScope,proto3" json:"agent_scope,omitempty"`
	Properties    *structpb.Struct       `protobuf:"bytes,8,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryEdge) Reset() {
	*x = MemoryEdge{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEdge) ProtoMessage() {}

func (x *MemoryEdge) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEdge.ProtoReflect.Descriptor instead.
func (*MemoryEdge) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryEdge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryEdge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *MemoryEdge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MemoryEdge) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *MemoryEdge) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *MemoryEdge) GetTemporal() *TemporalInfo {
	if x != nil {
		return x.Temporal
	}
	return nil
}

func (x *MemoryEdge) GetAgentScope() *AgentScope {
	if x != nil {
		return x.AgentScope
	}
	return nil
}

func (x *MemoryEdge) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Scope Filter for Queries
type AdapterScopeFilter struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CallerAdapterId       string                 `protobuf:"bytes,1,opt,name=caller_adapter_id,json=callerAdapterId,proto3" json:"caller_adapter_id,omitempty"`                    // Identity of the querying adapter
	TargetAdapterIds      []string               `protobuf:"bytes,2,rep,name=target_adapter_ids,json=targetAdapterIds,proto3" json:"target_adapter_ids,omitempty"`                 // List of adapter IDs to query, or ["*"] for all
	IncludeWorkflowShared bool                   `protobuf:"varint,3,opt,name=include_workflow_shared,json=includeWorkflowShared,proto3" json:"include_workflow_shared,omitempty"` // Include memories marked VISIBILITY_WORKFLOW
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AdapterScopeFilter) Reset() {
	*x = AdapterScopeFilter{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterScopeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterScopeFilter) ProtoMessage() {}

func (x *AdapterScopeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterScopeFilter.ProtoReflect.Descriptor instead.
func (*AdapterScopeFilter) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{6}
}

func (x *AdapterScopeFilter) GetCallerAdapterId() string {
	if x != nil {
		return x.CallerAdapterId
	}
	return ""
}

func (x *AdapterScopeFilter) GetTargetAdapterIds() []string {
	if x != nil {
		return x.TargetAdapterIds
	}
	return nil
}

func (x *AdapterScopeFilter) GetIncludeWorkflowShared() bool {
	if x != nil {
		return x.IncludeWorkflowShared
	}
	return false
}

// Temporal Filter for Queries
type TemporalQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValidAt       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=valid_at,json=validAt,proto3" json:"valid_at,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	TenseFilter   Tense                  `protobuf:"varint,4,opt,name=tense_filter,json=tenseFilter,proto3,enum=criteriadb.v1.Tense" json:"tense_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemporalQuery) Reset() {
	*x = TemporalQuery{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporalQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporalQuery) ProtoMessage() {}

func (x *TemporalQuery) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporalQuery.ProtoReflect.Descriptor instead.
func (*TemporalQuery) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{7}
}

func (x *TemporalQuery) GetValidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidAt
	}
	return nil
}

func (x *TemporalQuery) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TemporalQuery) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TemporalQuery) GetTenseFilter() Tense {
	if x != nil {
		return x.TenseFilter
	}
	return Tense_TENSE_UNSPECIFIED
}

// Digital & Physical Location Filter
type LocationQuery struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MatchProject      string                 `protobuf:"bytes,1,opt,name=match_project,json=matchProject,proto3" json:"match_project,omitempty"`
	MatchFolderPrefix string                 `protobuf:"bytes,2,opt,name=match_folder_prefix,json=matchFolderPrefix,proto3" json:"match_folder_prefix,omitempty"`
	MatchMachine      string                 `protobuf:"bytes,3,opt,name=match_machine,json=matchMachine,proto3" json:"match_machine,omitempty"`
	MatchVenue        string                 `protobuf:"bytes,4,opt,name=match_venue,json=matchVenue,proto3" json:"match_venue,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LocationQuery) Reset() {
	*x = LocationQuery{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationQuery) ProtoMessage() {}

func (x *LocationQuery) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationQuery.ProtoReflect.Descriptor instead.
func (*LocationQuery) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{8}
}

func (x *LocationQuery) GetMatchProject() string {
	if x != nil {
		return x.MatchProject
	}
	return ""
}

func (x *LocationQuery) GetMatchFolderPrefix() string {
	if x != nil {
		return x.MatchFolderPrefix
	}
	return ""
}

func (x *LocationQuery) GetMatchMachine() string {
	if x != nil {
		return x.MatchMachine
	}
	return ""
}

func (x *LocationQuery) GetMatchVenue() string {
	if x != nil {
		return x.MatchVenue
	}
	return ""
}

// Fact Filter for Graph Traversal
type FactQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelationTypes []string               `protobuf:"bytes,1,rep,name=relation_types,json=relationTypes,proto3" json:"relation_types,omitempty"`
	MaxHops       int32                  `protobuf:"varint,2,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	TargetLabel   string                 `protobuf:"bytes,3,opt,name=target_label,json=targetLabel,proto3" json:"target_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactQuery) Reset() {
	*x = FactQuery{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactQuery) ProtoMessage() {}

func (x *FactQuery) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactQuery.ProtoReflect.Descriptor instead.
func (*FactQuery) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{9}
}

func (x *FactQuery) GetRelationTypes() []string {
	if x != nil {
		return x.RelationTypes
	}
	return nil
}

func (x *FactQuery) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *FactQuery) GetTargetLabel() string {
	if x != nil {
		return x.TargetLabel
	}
	return ""
}

// Multi-Modal Query Request
type QueryRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	QueryText            string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	PackedQueryEmbedding []byte                 `protobuf:"bytes,2,opt,name=packed_query_embedding,json=packedQueryEmbedding,proto3" json:"packed_query_embedding,omitempty"` // Optional float32 vector
	ScopeFilter          *AdapterScopeFilter    `protobuf:"bytes,3,opt,name=scope_filter,json=scopeFilter,proto3" json:"scope_filter,omitempty"`
	TemporalFilter       *TemporalQuery         `protobuf:"bytes,4,opt,name=temporal_filter,json=temporalFilter,proto3" json:"temporal_filter,omitempty"`
	LocationFilter       *LocationQuery         `protobuf:"bytes,5,opt,name=location_filter,json=locationFilter,proto3" json:"location_filter,omitempty"`
	FactFilter           *FactQuery             `protobuf:"bytes,6,opt,name=fact_filter,json=factFilter,proto3" json:"fact_filter,omitempty"`
	Limit                int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	DisableVectorSearch  bool                   `protobuf:"varint,8,opt,name=disable_vector_search,json=disableVectorSearch,proto3" json:"disable_vector_search,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{10}
}

func (x *QueryRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *QueryRequest) GetPackedQueryEmbedding() []byte {
	if x != nil {
		return x.PackedQueryEmbedding
	}
	return nil
}

func (x *QueryRequest) GetScopeFilter() *AdapterScopeFilter {
	if x != nil {
		return x.ScopeFilter
	}
	return nil
}

func (x *QueryRequest) GetTemporalFilter() *TemporalQuery {
	if x != nil {
		return x.TemporalFilter
	}
	return nil
}

func (x *QueryRequest) GetLocationFilter() *LocationQuery {
	if x != nil {
		return x.LocationFilter
	}
	return nil
}

func (x *QueryRequest) GetFactFilter() *FactQuery {
	if x != nil {
		return x.FactFilter
	}
	return nil
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetDisableVectorSearch() bool {
	if x != nil {
		return x.DisableVectorSearch
	}
	return false
}

type MemoryQueryResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Node           *MemoryNode            `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	ConnectedEdges []*MemoryEdge          `protobuf:"bytes,2,rep,name=connected_edges,json=connectedEdges,proto3" json:"connected_edges,omitempty"`
	Score          float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	LexicalScore   float64                `protobuf:"fixed64,4,opt,name=lexical_score,json=lexicalScore,proto3" json:"lexical_score,omitempty"`
	VectorScore    float64                `protobuf:"fixed64,5,opt,name=vector_score,json=vectorScore,proto3" json:"vector_score,omitempty"`
	TemporalScore  float64                `protobuf:"fixed64,6,opt,name=temporal_score,json=temporalScore,proto3" json:"temporal_score,omitempty"`
	LocationScore  float64                `protobuf:"fixed64,7,opt,name=location_score,json=locationScore,proto3" json:"location_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryQueryResult) Reset() {
	*x = MemoryQueryResult{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryQueryResult) ProtoMessage() {}

func (x *MemoryQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryQueryResult.ProtoReflect.Descriptor instead.
func (*MemoryQueryResult) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{11}
}

func (x *MemoryQueryResult) GetNode() *MemoryNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *MemoryQueryResult) GetConnectedEdges() []*MemoryEdge {
	if x != nil {
		return x.ConnectedEdges
	}
	return nil
}

func (x *MemoryQueryResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MemoryQueryResult) GetLexicalScore() float64 {
	if x != nil {
		return x.LexicalScore
	}
	return 0
}

func (x *MemoryQueryResult) GetVectorScore() float64 {
	if x != nil {
		return x.VectorScore
	}
	return 0
}

func (x *MemoryQueryResult) GetTemporalScore() float64 {
	if x != nil {
		return x.TemporalScore
	}
	return 0
}

func (x *MemoryQueryResult) GetLocationScore() float64 {
	if x != nil {
		return x.LocationScore
	}
	return 0
}

type RememberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *MemoryNode            `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Edges         []*MemoryEdge          `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberRequest) Reset() {
	*x = RememberRequest{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberRequest) ProtoMessage() {}

func (x *RememberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberRequest.ProtoReflect.Descriptor instead.
func (*RememberRequest) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{12}
}

func (x *RememberRequest) GetNode() *MemoryNode {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *RememberRequest) GetEdges() []*MemoryEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type RememberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RememberResponse) Reset() {
	*x = RememberResponse{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RememberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RememberResponse) ProtoMessage() {}

func (x *RememberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RememberResponse.ProtoReflect.Descriptor instead.
func (*RememberResponse) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{13}
}

func (x *RememberResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RememberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MemoryQueryResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_criteriadb_v1_criteriadb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_criteriadb_v1_criteriadb_proto_rawDescGZIP(), []int{14}
}

func (x *QueryResponse) GetResults() []*MemoryQueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_criteriadb_v1_criteriadb_proto protoreflect.FileDescriptor

const file_criteriadb_v1_criteriadb_proto_rawDesc = "" +
	"\n" +
	"\x1ecriteriadb/v1/criteriadb.proto\x12\rcriteriadb.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x9d\x02\n" +
	"\fTemporalInfo\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\n" +
	"valid_from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x125\n" +
	"\bdue_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12*\n" +
	"\x05tense\x18\x05 \x01(\x0e2\x14.criteriadb.v1.TenseR\x05tense\"\xc4\x01\n" +
	"\x0fDigitalLocation\x12\x18\n" +
	"\amachine\x18\x01 \x01(\tR\amachine\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x18\n" +
	"\aproject\x18\x03 \x01(\tR\aproject\x12\x1f\n" +
	"\vfolder_path\x18\x04 \x01(\tR\n" +
	"folderPath\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1f\n" +
	"\vservice_url\x18\x06 \x01(\tR\n" +
	"serviceUrl\"|\n" +
	"\x10PhysicalLocation\x12\x14\n" +
	"\x05venue\x18\x01 \x01(\tR\x05venue\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"\xd6\x01\n" +
	"\n" +
	"AgentScope\x12,\n" +
	"\x12creator_adapter_id\x18\x01 \x01(\tR\x10creatorAdapterId\x120\n" +
	"\x14creator_adapter_type\x18\x02 \x01(\tR\x12creatorAdapterType\x12(\n" +
	"\x10creator_agent_id\x18\x03 \x01(\tR\x0ecreatorAgentId\x12>\n" +
	"\n" +
	"visibility\x18\x04 \x01(\x0e2\x1e.criteriadb.v1.VisibilityScopeR\n" +
	"visibility\"\xfd\x03\n" +
	"\n" +
	"MemoryNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12)\n" +
	"\x10packed_embedding\x18\x05 \x01(\fR\x0fpackedEmbedding\x12)\n" +
	"\x10vector_dimension\x18\x06 \x01(\x05R\x0fvectorDimension\x127\n" +
	"\btemporal\x18\a \x01(\v2\x1b.criteriadb.v1.TemporalInfoR\btemporal\x12I\n" +
	"\x10digital_location\x18\b \x01(\v2\x1e.criteriadb.v1.DigitalLocationR\x0fdigitalLocation\x12L\n" +
	"\x11physical_location\x18\t \x01(\v2\x1f.criteriadb.v1.PhysicalLocationR\x10physicalLocation\x12:\n" +
	"\vagent_scope\x18\n" +
	" \x01(\v2\x19.criteriadb.v1.AgentScopeR\n" +
	"agentScope\x127\n" +
	"\n" +
	"properties\x18\v \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"\xb8\x02\n" +
	"\n" +
	"MemoryEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12\x1a\n" +
	"\brelation\x18\x04 \x01(\tR\brelation\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x127\n" +
	"\btemporal\x18\x06 \x01(\v2\x1b.criteriadb.v1.TemporalInfoR\btemporal\x12:\n" +
	"\vagent_scope\x18\a \x01(\v2\x19.criteriadb.v1.AgentScopeR\n" +
	"agentScope\x127\n" +
	"\n" +
	"properties\x18\b \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\"\xa6\x01\n" +
	"\x12AdapterScopeFilter\x12*\n" +
	"\x11caller_adapter_id\x18\x01 \x01(\tR\x0fcallerAdapterId\x12,\n" +
	"\x12target_adapter_ids\x18\x02 \x03(\tR\x10targetAdapterIds\x126\n" +
	"\x17include_workflow_shared\x18\x03 \x01(\bR\x15includeWorkflowShared\"\xf1\x01\n" +
	"\rTemporalQuery\x125\n" +
	"\bvalid_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\avalidAt\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x127\n" +
	"\ftense_filter\x18\x04 \x01(\x0e2\x14.criteriadb.v1.TenseR\vtenseFilter\"\xaa\x01\n" +
	"\rLocationQuery\x12#\n" +
	"\rmatch_project\x18\x01 \x01(\tR\fmatchProject\x12.\n" +
	"\x13match_folder_prefix\x18\x02 \x01(\tR\x11matchFolderPrefix\x12#\n" +
	"\rmatch_machine\x18\x03 \x01(\tR\fmatchMachine\x12\x1f\n" +
	"\vmatch_venue\x18\x04 \x01(\tR\n" +
	"matchVenue\"p\n" +
	"\tFactQuery\x12%\n" +
	"\x0erelation_types\x18\x01 \x03(\tR\rrelationTypes\x12\x19\n" +
	"\bmax_hops\x18\x02 \x01(\x05R\amaxHops\x12!\n" +
	"\ftarget_label\x18\x03 \x01(\tR\vtargetLabel\"\xbc\x03\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x124\n" +
	"\x16packed_query_embedding\x18\x02 \x01(\fR\x14packedQueryEmbedding\x12D\n" +
	"\fscope_filter\x18\x03 \x01(\v2!.criteriadb.v1.AdapterScopeFilterR\vscopeFilter\x12E\n" +
	"\x0ftemporal_filter\x18\x04 \x01(\v2\x1c.criteriadb.v1.TemporalQueryR\x0etemporalFilter\x12E\n" +
	"\x0flocation_filter\x18\x05 \x01(\v2\x1c.criteriadb.v1.LocationQueryR\x0elocationFilter\x129\n" +
	"\vfact_filter\x18\x06 \x01(\v2\x18.criteriadb.v1.FactQueryR\n" +
	"factFilter\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x122\n" +
	"\x15disable_vector_search\x18\b \x01(\bR\x13disableVectorSearch\"\xb2\x02\n" +
	"\x11MemoryQueryResult\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.criteriadb.v1.MemoryNodeR\x04node\x12B\n" +
	"\x0fconnected_edges\x18\x02 \x03(\v2\x19.criteriadb.v1.MemoryEdgeR\x0econnectedEdges\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12#\n" +
	"\rlexical_score\x18\x04 \x01(\x01R\flexicalScore\x12!\n" +
	"\fvector_score\x18\x05 \x01(\x01R\vvectorScore\x12%\n" +
	"\x0etemporal_score\x18\x06 \x01(\x01R\rtemporalScore\x12%\n" +
	"\x0elocation_score\x18\a \x01(\x01R\rlocationScore\"q\n" +
	"\x0fRememberRequest\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.criteriadb.v1.MemoryNodeR\x04node\x12/\n" +
	"\x05edges\x18\x02 \x03(\v2\x19.criteriadb.v1.MemoryEdgeR\x05edges\"E\n" +
	"\x10RememberResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"K\n" +
	"\rQueryResponse\x12:\n" +
	"\aresults\x18\x01 \x03(\v2 .criteriadb.v1.MemoryQueryResultR\aresults*}\n" +
	"\x05Tense\x12\x15\n" +
	"\x11TENSE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"TENSE_PAST\x10\x01\x12\x11\n" +
	"\rTENSE_PRESENT\x10\x02\x12\x10\n" +
	"\fTENSE_FUTURE\x10\x03\x12\x11\n" +
	"\rTENSE_PLANNED\x10\x04\x12\x15\n" +
	"\x11TENSE_CONDITIONAL\x10\x05*Y\n" +
	"\x0fVisibilityScope\x12\x16\n" +
	"\x12VISIBILITY_PRIVATE\x10\x00\x12\x17\n" +
	"\x13VISIBILITY_WORKFLOW\x10\x01\x12\x15\n" +
	"\x11VISIBILITY_GLOBAL\x10\x022\xa1\x01\n" +
	"\rMemoryService\x12K\n" +
	"\bRemember\x12\x1e.criteriadb.v1.RememberRequest\x1a\x1f.criteriadb.v1.RememberResponse\x12C\n" +
	"\x06Recall\x12\x1b.criteriadb.v1.QueryRequest\x1a\x1c.criteriadb.v1.QueryResponseBDZBgithub.com/brokenbots/criteriadb/pkg/pb/criteriadb/v1;criteriadbv1b\x06proto3"

var (
	file_criteriadb_v1_criteriadb_proto_rawDescOnce sync.Once
	file_criteriadb_v1_criteriadb_proto_rawDescData []byte
)

func file_criteriadb_v1_criteriadb_proto_rawDescGZIP() []byte {
	file_criteriadb_v1_criteriadb_proto_rawDescOnce.Do(func() {
		file_criteriadb_v1_criteriadb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_criteriadb_v1_criteriadb_proto_rawDesc), len(file_criteriadb_v1_criteriadb_proto_rawDesc)))
	})
	return file_criteriadb_v1_criteriadb_proto_rawDescData
}

var file_criteriadb_v1_criteriadb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_criteriadb_v1_criteriadb_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_criteriadb_v1_criteriadb_proto_goTypes = []any{
	(Tense)(0),                    // 0: criteriadb.v1.Tense
	(VisibilityScope)(0),          // 1: criteriadb.v1.VisibilityScope
	(*TemporalInfo)(nil),          // 2: criteriadb.v1.TemporalInfo
	(*DigitalLocation)(nil),       // 3: criteriadb.v1.DigitalLocation
	(*PhysicalLocation)(nil),      // 4: criteriadb.v1.PhysicalLocation
	(*AgentScope)(nil),            // 5: criteriadb.v1.AgentScope
	(*MemoryNode)(nil),            // 6: criteriadb.v1.MemoryNode
	(*MemoryEdge)(nil),            // 7: criteriadb.v1.MemoryEdge
	(*AdapterScopeFilter)(nil),    // 8: criteriadb.v1.AdapterScopeFilter
	(*TemporalQuery)(nil),         // 9: criteriadb.v1.TemporalQuery
	(*LocationQuery)(nil),         // 10: criteriadb.v1.LocationQuery
	(*FactQuery)(nil),             // 11: criteriadb.v1.FactQuery
	(*QueryRequest)(nil),          // 12: criteriadb.v1.QueryRequest
	(*MemoryQueryResult)(nil),     // 13: criteriadb.v1.MemoryQueryResult
	(*RememberRequest)(nil),       // 14: criteriadb.v1.RememberRequest
	(*RememberResponse)(nil),      // 15: criteriadb.v1.RememberResponse
	(*QueryResponse)(nil),         // 16: criteriadb.v1.QueryResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 18: google.protobuf.Struct
}
var file_criteriadb_v1_criteriadb_proto_depIdxs = []int32{
	17, // 0: criteriadb.v1.TemporalInfo.timestamp:type_name -> google.protobuf.Timestamp
	17, // 1: criteriadb.v1.TemporalInfo.valid_from:type_name -> google.protobuf.Timestamp
	17, // 2: criteriadb.v1.TemporalInfo.valid_to:type_name -> google.protobuf.Timestamp
	17, // 3: criteriadb.v1.TemporalInfo.due_date:type_name -> google.protobuf.Timestamp
	0,  // 4: criteriadb.v1.TemporalInfo.tense:type_name -> criteriadb.v1.Tense
	1,  // 5: criteriadb.v1.AgentScope.visibility:type_name -> criteriadb.v1.VisibilityScope
	2,  // 6: criteriadb.v1.MemoryNode.temporal:type_name -> criteriadb.v1.TemporalInfo
	3,  // 7: criteriadb.v1.MemoryNode.digital_location:type_name -> criteriadb.v1.DigitalLocation
	4,  // 8: criteriadb.v1.MemoryNode.physical_location:type_name -> criteriadb.v1.PhysicalLocation
	5,  // 9: criteriadb.v1.MemoryNode.agent_scope:type_name -> criteriadb.v1.AgentScope
	18, // 10: criteriadb.v1.MemoryNode.properties:type_name -> google.protobuf.Struct
	2,  // 11: criteriadb.v1.MemoryEdge.temporal:type_name -> criteriadb.v1.TemporalInfo
	5,  // 12: criteriadb.v1.MemoryEdge.agent_scope:type_name -> criteriadb.v1.AgentScope
	18, // 13: criteriadb.v1.MemoryEdge.properties:type_name -> google.protobuf.Struct
	17, // 14: criteriadb.v1.TemporalQuery.valid_at:type_name -> google.protobuf.Timestamp
	17, // 15: criteriadb.v1.TemporalQuery.start_time:type_name -> google.protobuf.Timestamp
	17, // 16: criteriadb.v1.TemporalQuery.end_time:type_name -> google.protobuf.Timestamp
	0,  // 17: criteriadb.v1.TemporalQuery.tense_filter:type_name -> criteriadb.v1.Tense
	8,  // 18: criteriadb.v1.QueryRequest.scope_filter:type_name -> criteriadb.v1.AdapterScopeFilter
	9,  // 19: criteriadb.v1.QueryRequest.temporal_filter:type_name -> criteriadb.v1.TemporalQuery
	10, // 20: criteriadb.v1.QueryRequest.location_filter:type_name -> criteriadb.v1.LocationQuery
	11, // 21: criteriadb.v1.QueryRequest.fact_filter:type_name -> criteriadb.v1.FactQuery
	6,  // 22: criteriadb.v1.MemoryQueryResult.node:type_name -> criteriadb.v1.MemoryNode
	7,  // 23: criteriadb.v1.MemoryQueryResult.connected_edges:type_name -> criteriadb.v1.MemoryEdge
	6,  // 24: criteriadb.v1.RememberRequest.node:type_name -> criteriadb.v1.MemoryNode
	7,  // 25: criteriadb.v1.RememberRequest.edges:type_name -> criteriadb.v1.MemoryEdge
	13, // 26: criteriadb.v1.QueryResponse.results:type_name -> criteriadb.v1.MemoryQueryResult
	14, // 27: criteriadb.v1.MemoryService.Remember:input_type -> criteriadb.v1.RememberRequest
	12, // 28: criteriadb.v1.MemoryService.Recall:input_type -> criteriadb.v1.QueryRequest
	15, // 29: criteriadb.v1.MemoryService.Remember:output_type -> criteriadb.v1.RememberResponse
	16, // 30: criteriadb.v1.MemoryService.Recall:output_type -> criteriadb.v1.QueryResponse
	29, // [29:31] is the sub-list for method output_type
	27, // [27:29] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_criteriadb_v1_criteriadb_proto_init() }
func file_criteriadb_v1_criteriadb_proto_init() {
	if File_criteriadb_v1_criteriadb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_criteriadb_v1_criteriadb_proto_rawDesc), len(file_criteriadb_v1_criteriadb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_criteriadb_v1_criteriadb_proto_goTypes,
		DependencyIndexes: file_criteriadb_v1_criteriadb_proto_depIdxs,
		EnumInfos:         file_criteriadb_v1_criteriadb_proto_enumTypes,
		MessageInfos:      file_criteriadb_v1_criteriadb_proto_msgTypes,
	}.Build()
	File_criteriadb_v1_criteriadb_proto = out.File
	file_criteriadb_v1_criteriadb_proto_goTypes = nil
	file_criteriadb_v1_criteriadb_proto_depIdxs = nil
}
